from __future__ import annotations

import csv
import hashlib
import json
import shutil
import sys
import tempfile
from importlib import import_module
from pathlib import Path
from typing import Any

from paperkit import __version__
from paperkit.claims import evaluate_claims, load_claims
from paperkit.config import ProjectConfig, load_yaml
from paperkit.publication import render_claim_table, render_project_metadata


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode()


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(_json_bytes(value))


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def _write_summary_csv(path: Path, results: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["metric", "value"])
        for key in sorted(results):
            if isinstance(results[key], int | float | str | bool):
                writer.writerow([key, results[key]])


def _write_result_macros(path: Path, results: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% Generated by paperkit. Do not edit."]
    for key in sorted(results):
        value = results[key]
        if isinstance(value, int | float):
            command = "".join(part.capitalize() for part in key.split("_"))
            rendered = f"{value:.12g}" if isinstance(value, float) else str(value)
            lines.append(f"\\newcommand{{\\Result{command}}}{{{rendered}}}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _load_analysis(root: Path, import_name: str) -> Any:
    package_source = str(root / "packages" / "python" / "src")
    if package_source not in sys.path:
        sys.path.insert(0, package_source)
    return import_module(f"{import_name}.analysis")


def _conformance_vectors(analysis: Any) -> dict[str, Any]:
    inputs = [
        {
            "offers": [{"available": True, "price": 7, "api_calls": 1}],
            "policy": "accept_first",
        },
        {
            "offers": [
                {"available": True, "price": 6, "api_calls": 1},
                {"available": True, "price": 2, "api_calls": 1},
            ],
            "policy": "resource_aware_threshold",
            "threshold": 2,
        },
        {
            "offers": [
                {"available": False, "price": None, "api_calls": 1},
                {"available": True, "price": 5, "api_calls": 1},
            ],
            "policy": "accept_first",
        },
        {
            "offers": [
                {"available": True, "price": 6, "api_calls": 1},
                {"available": True, "price": 2, "api_calls": 1},
            ],
            "policy": "fixed_threshold",
            "threshold": 2,
            "budget": {"api_calls": 1},
        },
    ]
    cases = [
        {"input": value, "expected": analysis.simulate_policy(**value).as_dict()}
        for value in inputs
    ]
    planner_inputs = [
        {
            "merchants": [
                {
                    "price_weights": [{"price": 100, "weight": 1}],
                    "time": 1,
                    "tokens": 1,
                    "api_calls": 1,
                },
                {
                    "price_weights": [{"price": 50, "weight": 1}],
                    "time": 5,
                    "tokens": 1,
                    "api_calls": 1,
                },
                {
                    "price_weights": [{"price": 60, "weight": 1}],
                    "time": 1,
                    "tokens": 5,
                    "api_calls": 1,
                },
            ],
            "budget": {"time": 2, "tokens": 10, "api_calls": 2, "api_cost": 0},
            "observedPrice": 100,
            "maxPurchasePrice": 150,
            "failurePenalty": 180,
        },
        {
            "merchants": [
                {
                    "price_weights": [{"price": 100, "weight": 1}],
                    "api_calls": 1,
                },
                {
                    "price_weights": [{"price": 60, "weight": 1}],
                    "api_calls": 1,
                },
            ],
            "budget": {"time": 0, "tokens": 0, "api_calls": 1, "api_cost": 0},
            "observedPrice": 100,
            "maxPurchasePrice": 90,
            "failurePenalty": 180,
        },
    ]
    planner_cases = []
    for value in planner_inputs:
        plan = analysis.adaptive_hard_budget_plan(
            value["merchants"],
            value["budget"],
            value["maxPurchasePrice"],
            value["failurePenalty"],
        )
        reservation = plan["reservation_price"]["value"]
        if value["observedPrice"] <= reservation:
            action = "buy"
        elif plan["next_merchant_index"] is None:
            action = "reject_without_feasible_query"
        else:
            action = "continue"
        planner_cases.append(
            {
                "input": value,
                "expected": {
                    "action": action,
                    "reservation_price": reservation,
                    "continuation_value": plan["continuation_value"]["value"],
                    "next_merchant_index": plan["next_merchant_index"],
                    "feasible_next_merchants": plan["feasible_next_merchants"],
                    "remaining_after_observation": plan["remaining_after_observation"],
                },
            }
        )
    return {
        "schema_version": 1,
        "operation": "simulate_policy",
        "cases": cases,
        "planner_cases": planner_cases,
        "errors": [
            {
                "input": {
                    "offers": [{"available": True, "price": None}],
                    "policy": "accept_first",
                },
                "type": "ValueError",
            },
            {
                "input": {"offers": [], "policy": "unknown"},
                "type": "ValueError",
            },
        ],
    }


def build(root: Path, output_dir: Path | None = None) -> Path:
    root = root.resolve()
    destination = (output_dir or root / "artifacts").resolve()
    config = ProjectConfig.from_file(root / "project.yml")
    claims = load_claims(root / "research" / "claims.yml")
    analysis = _load_analysis(root, config.python_import_name)
    results = analysis.run_analysis(seed=config.random_seed)
    evaluations = evaluate_claims(results, claims)

    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix="paperkit-", dir=destination.parent))
    try:
        _write_json(staging / "results.json", results)
        _write_json(staging / "claim-results.json", {"claims": evaluations})
        _write_json(
            staging / "conformance" / "merchant-search.json",
            _conformance_vectors(analysis),
        )
        raw_project = load_yaml(root / "project.yml")
        _write_json(
            staging / "site-data.json",
            {
                "schema_version": 1,
                "initialized": config.initialized,
                "project": raw_project["project"],
                "authors": raw_project["authors"],
                "links": raw_project["links"],
                "licenses": raw_project["licenses"],
                "release": raw_project["release"],
                "packages": raw_project["packages"],
                "results": results,
                "claims": evaluations,
            },
        )
        _write_summary_csv(staging / "data" / "summary.csv", results)
        _write_result_macros(staging / "tables" / "result_macros.tex", results)
        (staging / "tables" / "project_metadata.tex").write_text(
            render_project_metadata(root / "project.yml"), encoding="utf-8"
        )
        (staging / "tables" / "claim_status.tex").write_text(
            render_claim_table(claims), encoding="utf-8"
        )

        files = sorted(path for path in staging.rglob("*") if path.is_file())
        manifest = {
            "schema_version": 1,
            "generator": {"name": "paperkit", "version": __version__},
            "project": {
                "slug": config.slug,
                "title": config.title,
                "version": config.version,
                "packages": {
                    "python": config.python_distribution,
                    "javascript": config.javascript_package,
                },
            },
            "random_seed": config.random_seed,
            "claims": [item["id"] for item in evaluations],
            "all_executable_claims_passed": all(item["passed"] for item in evaluations),
            "files": {
                path.relative_to(staging).as_posix(): _sha256(path)
                for path in files
            },
        }
        _write_json(staging / "manifest.json", manifest)

        backup = destination.with_name(f".{destination.name}.previous")
        if backup.exists():
            shutil.rmtree(backup)
        if destination.exists():
            destination.replace(backup)
        staging.replace(destination)
        if backup.exists():
            shutil.rmtree(backup)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return destination
