from __future__ import annotations

from pathlib import Path
from typing import Any

from paperkit.claims import Claim
from paperkit.config import ConfigurationError, load_yaml

LATEX_REPLACEMENTS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(value: str) -> str:
    return "".join(LATEX_REPLACEMENTS.get(character, character) for character in value)


def _required_mapping(value: Any, context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ConfigurationError(f"{context} must be a mapping")
    return value


def _required_text(mapping: dict[str, Any], key: str, context: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ConfigurationError(f"{context}.{key} must be a non-empty string")
    return value.strip()


def _newcommand(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def render_project_metadata(project_path: Path) -> str:
    raw = load_yaml(project_path)
    project = _required_mapping(raw.get("project"), "project")
    authors = raw.get("authors")
    if not isinstance(authors, list) or not authors:
        raise ConfigurationError("authors must be a non-empty list")

    author_parts: list[str] = []
    for index, author_value in enumerate(authors):
        author = _required_mapping(author_value, f"authors[{index}]")
        name = latex_escape(_required_text(author, "name", f"authors[{index}]"))
        affiliations = author.get("affiliations")
        if not isinstance(affiliations, list) or not affiliations:
            raise ConfigurationError(f"authors[{index}].affiliations must be a non-empty list")
        affiliation = latex_escape(str(affiliations[0]))
        author_parts.append(f"{name}\\\\{{\\small {affiliation}}}")

    keywords = project.get("keywords")
    categories = project.get("arxiv_categories")
    if not isinstance(keywords, list) or not isinstance(categories, list):
        raise ConfigurationError("project keywords and arxiv_categories must be lists")

    title = latex_escape(_required_text(project, "title", "project"))
    subtitle = latex_escape(_required_text(project, "subtitle", "project"))
    abstract = latex_escape(_required_text(project, "abstract", "project"))
    rendered_authors = r" \and ".join(author_parts)
    rendered_keywords = latex_escape(", ".join(map(str, keywords)))
    rendered_categories = latex_escape(", ".join(map(str, categories)))
    lines = [
        "% Generated by paperkit. Do not edit.",
        _newcommand("PaperTitle", title),
        _newcommand("PaperSubtitle", subtitle),
        _newcommand("PaperAuthors", rendered_authors),
        _newcommand("PaperAbstract", abstract),
        _newcommand("PaperKeywords", rendered_keywords),
        _newcommand("PaperArxivCategories", rendered_categories),
    ]
    return "\n".join(lines) + "\n"


def render_claim_table(claims: list[Claim]) -> str:
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{longtable}{@{}p{0.18\linewidth}p{0.18\linewidth}p{0.56\linewidth}@{}}",
        r"\toprule",
        r"Claim & Status & Scope \\",
        r"\midrule",
        r"\endhead",
    ]
    for claim in claims:
        lines.append(
            f"{latex_escape(claim.id)} & {latex_escape(claim.status)} & "
            f"{latex_escape(claim.scope)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}"])
    return "\n".join(lines) + "\n"


def render_bibliography(literature_path: Path) -> str:
    """Build a BibTeX file from verified literature records only.

    Only fields actually recorded during the verified search are emitted. Author and
    year are not stored, so they are not guessed; entries are numeric-cited `@misc`
    records carrying the title and the DOI that was checked.
    """
    raw = load_yaml(literature_path)
    works = raw.get("works")
    if not isinstance(works, list):
        raise ConfigurationError("literature.yml must contain a works list")

    lines = ["% Generated by paperkit from research/literature.yml. Do not edit."]
    for index, work in enumerate(works):
        record = _required_mapping(work, f"works[{index}]")
        key = _required_text(record, "citation_key", f"works[{index}]")
        title = _required_text(record, "title", key)
        url = _required_text(record, "url", key)
        verified = record.get("verified_on")
        note = f"Verified {verified}" if isinstance(verified, str) else "Verified record"
        lines.extend(
            [
                f"@misc{{{key},",
                f"  title = {{{{{title}}}}},",
                f"  howpublished = {{\\url{{{url}}}}},",
                f"  note = {{{note}}}",
                "}",
                "",
            ]
        )
    return "\n".join(lines) + "\n"


def render_rule_table(results: dict[str, Any]) -> str:
    """Render the head-to-head between the closed form, the solver, and n/e."""
    comparison = results["rule_comparison"]
    captured = comparison["savings_captured"]
    shown = (
        ("accept_first", "Accept first offer"),
        ("secretary_37", "Secretary rule ($n/e$)"),
        ("fixed_threshold", "Tuned fixed threshold"),
        ("closed_form", "Closed form (this paper)"),
        ("adaptive_stopping", "Exact solver"),
        ("exhaustive_oracle", "Offline oracle"),
    )
    arms = {arm["arm"]: arm for arm in comparison["arms"]}
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"Rule & Purchase loss & Savings captured & Queries \\",
        r"\midrule",
    ]
    for key, label in shown:
        arm = arms[key]
        lines.append(
            f"{label} & "
            f"{arm['mean_purchase_loss_minor']:.0f} & "
            f"{100 * captured[key]:.1f}\\% & "
            f"{arm['mean_query_count']:.2f} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def render_decision_table(results: dict[str, Any]) -> str:
    """Render the sweep as the practitioner-facing decision table."""
    verdict_labels = {
        "use_adaptive": "Adaptive",
        "use_fixed": "Fixed",
        "no_difference": "Either",
    }
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}rrrrl@{}}",
        r"\toprule",
        r"Merchants & Price spread & Budget & Improvement & Use \\",
        r"\midrule",
    ]
    for row in results["criteria"]["decision_table"]:
        improvement = row["relative_improvement"]
        lines.append(
            f"{row['merchant_count']} & "
            f"{row['dispersion_ratio']:.2f}$\\times$ & "
            f"{row['budget_fraction']:.2f} & "
            f"{100 * improvement:+.2f}\\% & "
            f"{verdict_labels[row['verdict']]} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def render_arm_table(results: dict[str, Any]) -> str:
    """Render the live-panel comparison of every policy arm."""
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"Policy & Purchase loss & Success rate & Queries \\",
        r"\midrule",
    ]
    for arm in results["real_study"]["arms"]:
        lines.append(
            f"{latex_escape(arm['arm'].replace('_', ' '))} & "
            f"{arm['mean_purchase_loss_minor']:.0f} & "
            f"{100 * arm['purchase_success_rate']:.1f}\\% & "
            f"{arm['mean_query_count']:.2f} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"
