from __future__ import annotations

from pathlib import Path
from typing import Any

from paperkit.claims import Claim
from paperkit.config import ConfigurationError, load_yaml

LATEX_REPLACEMENTS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(value: str) -> str:
    return "".join(LATEX_REPLACEMENTS.get(character, character) for character in value)


def _required_mapping(value: Any, context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ConfigurationError(f"{context} must be a mapping")
    return value


def _required_text(mapping: dict[str, Any], key: str, context: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ConfigurationError(f"{context}.{key} must be a non-empty string")
    return value.strip()


def _newcommand(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def render_project_metadata(project_path: Path) -> str:
    raw = load_yaml(project_path)
    project = _required_mapping(raw.get("project"), "project")
    authors = raw.get("authors")
    if not isinstance(authors, list) or not authors:
        raise ConfigurationError("authors must be a non-empty list")

    author_parts: list[str] = []
    for index, author_value in enumerate(authors):
        author = _required_mapping(author_value, f"authors[{index}]")
        name = latex_escape(_required_text(author, "name", f"authors[{index}]"))
        affiliations = author.get("affiliations")
        if not isinstance(affiliations, list) or not affiliations:
            raise ConfigurationError(f"authors[{index}].affiliations must be a non-empty list")
        affiliation = latex_escape(str(affiliations[0]))
        author_parts.append(f"{name}\\\\{{\\small {affiliation}}}")

    keywords = project.get("keywords")
    categories = project.get("arxiv_categories")
    if not isinstance(keywords, list) or not isinstance(categories, list):
        raise ConfigurationError("project keywords and arxiv_categories must be lists")

    title = latex_escape(_required_text(project, "title", "project"))
    subtitle = latex_escape(_required_text(project, "subtitle", "project"))
    abstract = latex_escape(_required_text(project, "abstract", "project"))
    rendered_authors = r" \and ".join(author_parts)
    rendered_keywords = latex_escape(", ".join(map(str, keywords)))
    rendered_categories = latex_escape(", ".join(map(str, categories)))
    lines = [
        "% Generated by paperkit. Do not edit.",
        _newcommand("PaperTitle", title),
        _newcommand("PaperSubtitle", subtitle),
        _newcommand("PaperAuthors", rendered_authors),
        _newcommand("PaperAbstract", abstract),
        _newcommand("PaperKeywords", rendered_keywords),
        _newcommand("PaperArxivCategories", rendered_categories),
    ]
    return "\n".join(lines) + "\n"


def render_claim_table(claims: list[Claim]) -> str:
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{longtable}{@{}p{0.18\linewidth}p{0.18\linewidth}p{0.56\linewidth}@{}}",
        r"\toprule",
        r"Claim & Status & Scope \\",
        r"\midrule",
        r"\endhead",
    ]
    for claim in claims:
        lines.append(
            f"{latex_escape(claim.id)} & {latex_escape(claim.status)} & "
            f"{latex_escape(claim.scope)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}"])
    return "\n".join(lines) + "\n"


def render_bibliography(literature_path: Path) -> str:
    """Build a BibTeX file from verified literature records only.

    Only fields actually recorded during the verified search are emitted. Author and
    year are not stored, so they are not guessed; entries are numeric-cited `@misc`
    records carrying the title and the DOI that was checked.
    """
    raw = load_yaml(literature_path)
    works = raw.get("works")
    if not isinstance(works, list):
        raise ConfigurationError("literature.yml must contain a works list")

    lines = ["% Generated by paperkit from research/literature.yml. Do not edit."]
    for index, work in enumerate(works):
        record = _required_mapping(work, f"works[{index}]")
        key = _required_text(record, "citation_key", f"works[{index}]")
        title = _required_text(record, "title", key)
        url = _required_text(record, "url", key)
        verified = record.get("verified_on")
        note = f"Verified {verified}" if isinstance(verified, str) else "Verified record"
        lines.extend(
            [
                f"@misc{{{key},",
                f"  title = {{{{{title}}}}},",
                f"  howpublished = {{\\url{{{url}}}}},",
                f"  note = {{{note}}}",
                "}",
                "",
            ]
        )
    return "\n".join(lines) + "\n"


def render_pandora_study_table(results: dict[str, Any]) -> str:
    """Render the held-out recalled-search comparison without inferring a win."""
    shopify = results["shopify_global_catalog"]
    costs = shopify.get("cost_results", [])
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}rrrrrl@{}}",
        r"\toprule",
        r"Scenario cost & Comparator & Difference & 95\% CI & Products & Status \\",
        r"\midrule",
    ]
    for row in costs:
        comparison = row["adaptive_vs_search_all"]
        scenario = latex_escape(str(row["cost_scenario"]).replace("_", " "))
        cost = float(row["inspection_cost_usd"])
        status = (
            "Adaptive improvement"
            if comparison["favors_treatment"]
            else "No reliable improvement"
        )
        lines.append(
            f"{scenario} (\\${cost:.2f}) & "
            "search all & "
            f"{comparison['mean_difference']:+.4f} & "
            f"[{comparison['ci_lower']:.4f}, {comparison['ci_upper']:.4f}] & "
            f"{comparison['product_clusters']} & {status} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def render_ucp_pandora_study_table(results: dict[str, Any]) -> str:
    """Render the repeated-date UCP panel replay without pooling it with Shopify."""
    replay = results["ucp_direct_panels"].get("pandora_replay", {})
    costs = replay.get("cost_results", [])
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}rrrrrl@{}}",
        r"\toprule",
        r"Scenario cost & Comparator & Difference & 95\% CI & SKU clusters & Status \\",
        r"\midrule",
    ]
    for row in costs:
        comparison = row["adaptive_vs_search_all"]
        scenario = latex_escape(str(row["cost_scenario"]).replace("_", " "))
        cost = float(row["inspection_cost_usd"])
        status = (
            "Adaptive improvement"
            if comparison["favors_treatment"]
            else "No reliable improvement"
        )
        lines.append(
            f"{scenario} (\\${cost:.2f}) & "
            "search all & "
            f"{comparison['mean_difference']:+.4f} & "
            f"[{comparison['ci_lower']:.4f}, {comparison['ci_upper']:.4f}] & "
            f"{comparison['product_clusters']} & {status} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def render_ucp_cost_sensitivity_table(results: dict[str, Any]) -> str:
    """Render complete-cost multipliers without implying observed billing."""
    sensitivity = results["ucp_cost_sensitivity"]
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}rrrrrl@{}}",
        r"\toprule",
        r"Cost multiple & Cost & Comparator & Difference & 95\% CI & Status \\",
        r"\midrule",
    ]
    for row in sensitivity["cost_results"]:
        comparison = row["adaptive_vs_search_all"]
        scenario = str(row["cost_scenario"])
        multiple = scenario.rsplit("_x", maxsplit=1)[-1]
        if comparison["favors_treatment"]:
            status = "Adaptive improvement"
        elif comparison["ci_lower"] > 0:
            status = "Search-all improvement"
        else:
            status = "No reliable improvement"
        lines.append(
            f"{multiple}$\\times$ & \\${row['inspection_cost_usd']:.5f} & "
            "search all & "
            f"{comparison['mean_difference']:+.4f} & "
            f"[{comparison['ci_lower']:.4f}, {comparison['ci_upper']:.4f}] & {status} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def render_source_table(results: dict[str, Any]) -> str:
    """Render separate source roles rather than pooling incompatible observations."""
    shopify = results["shopify_global_catalog"]
    ucp = results["ucp_direct_panels"]
    deck_count = shopify.get("product_deck_count", 0)
    seller_count = shopify.get("seller_card_count", 0)
    included_dates = ucp.get("included_lifecycle_dates", [])
    excluded_dates = ucp.get("excluded_dates", {})
    cost_overlay = ucp.get("cost_overlay", {})
    probe_calls = cost_overlay.get("total_merchant_probe_calls", 0)
    scenario_count = len(cost_overlay.get("scenarios", []))
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{tabular}{@{}p{0.24\linewidth}p{0.32\linewidth}p{0.34\linewidth}@{}}",
        r"\toprule",
        r"Source & What it supplies & Reporting role \\",
        r"\midrule",
        "Shopify Global Catalog & "
        f"{deck_count} seller decks; {seller_count} seller cards; one frozen USD snapshot & "
        "Exploratory free-recall Pandora replay; no advantage claim. \\\\",
        "UCP direct merchant panels & "
        f"{len(included_dates)} lifecycle dates; "
        f"{len(excluded_dates)} common-mode dates excluded & "
        f"{probe_calls} merchant probes costed under {scenario_count} declared scenarios; "
        "catalog observability context, not pooled with Shopify decks. \\\\"
    ]
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"
